


```python
# --- Angel One API Credentials ---
API_KEY = "YOUR_API_KEY"
SECRET_KEY = "YOUR_SECRET_KEY"
CLIENT_ID = "YOUR_CLIENT_ID"
PASSWORD = "YOUR_LOGIN_PASSWORD"
TOTP_SECRET = "YOUR_TOTP_SECRET"


